### ISSUE TITLE
Android Wear - Moto360 crash on startup

### ISSUE THREAD

**Issue by clhols** [toggl/mobile#1807]
The app crashes on startup with the following exception:

08-10 16:53:00.631 5710-5710/? W/monodroid: Trying to load sgen from: /data/app/com.toggl.timer-1/lib/arm/libmonosgen-2.0.so
08-10 16:53:00.773 5710-5710/? W/monodroid-gc: GREF GC Threshold: 46080
08-10 16:53:02.628 5710-5710/? I/MonoDroid: UNHANDLED EXCEPTION:
08-10 16:53:02.661 5710-5710/? I/MonoDroid: System.NullReferenceException: Object reference not set to an instance of an object
08-10 16:53:02.661 5710-5710/? I/MonoDroid:   at Toggl.Chandler.UI.Activities.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) <0xab67a670 + 0x000cc> in <filename unknown>:0 
08-10 16:53:02.661 5710-5710/? I/MonoDroid:   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) <0xab67a2f8 + 0x0006b> in <filename unknown>:0 
08-10 16:53:02.661 5710-5710/? I/MonoDroid:     at (wrapper dynamic-method) System.Object:c3e3b338-6087-47d2-a435-463fc118ac5a (intptr,intptr,intptr)
08-10 16:53:02.682 5710-5710/? W/art: JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
08-10 16:53:02.691 5710-5710/? D/AndroidRuntime: Shutting down VM
08-10 16:53:02.713 5710-5710/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.toggl.timer, PID: 5710
                                                 java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                  Caused by: java.lang.reflect.InvocationTargetException
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                  Caused by: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
                                                   at Toggl.Chandler.UI.Activities.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) <0xab67a670 + 0x000cc> in <filename unknown>:0 
                                                   at Android.App.Activity.n_OnCreate_Landroid_os_Bundle_ (IntPtr jnienv, IntPtr native__this, IntPtr native_savedInstanceState) <0xab67a2f8 + 0x0006b> in <filename unknown>:0 
                                                     at (wrapper dynamic-method) System.Object:c3e3b338-6087-47d2-a435-463fc118ac5a (intptr,intptr,intptr)
                                                     at md532180f774cdaabd03ff1344b502b0625.MainActivity.n_onCreate(Native Method)
                                                     at md532180f774cdaabd03ff1344b502b0625.MainActivity.onCreate(MainActivity.java:38)
                                                     at android.app.Activity.performCreate(Activity.java:6251)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:148)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5422)
                                                     	... 3 more
08-10 16:53:02.717 1806-2109/? W/ActivityManager:   Force finishing activity com.toggl.timer/md532180f774cdaabd03ff1344b502b0625.MainActivity

**Comment by clhols** [comment]
Android Wear version is 6.0.1.
Toggl Android version is 8.1.5

**Comment by willsb** [comment]
Confirmed this bug on my own Moto360. Also, this is fixed in the current unidirectional branch. Expect a new store version soon :)

**Comment by retog** [comment]
@willsb, 3 month later it still appears not to be working. Any eta for the fix to be in the store version?

**Comment by amatsegor** [comment]
Confirm, the crash is still here
But works in beta version (https://tsfr.io/xrkvaq)
